"""
agent_os/common/__init__.py
公开 API 入口。
"""

from .config import LlmGatewayConfig, MemoryConfig, RuntimeConfig
from .enums import (
    ActorResponseType,
    CollaborationStrategy,
    MemorySource,
    MemoryType,
    TaskStatus,
    ToolCategory,
)
from .event_bus import InMemoryEventBus
from .events import (
    StepProgress,
    TaskCompleted,
    TaskCreated,
    TaskFailed,
    TaskResumed,
    TaskStarted,
    TaskUnblocked,
    TaskWaitingDependency,
    TaskWaitingInput,
)
from .exceptions import (
    ActorDefinitionError,
    ActorNotFoundError,
    CircularDependencyError,
    ContextBuildError,
    DependencyNotFoundError,
    DuplicateActorError,
    DuplicateRefIdError,
    DuplicateToolError,
    GroupStateSerializationError,
    InvalidActorError,
    InvalidStatusTransitionError,
    InvalidTaskStateError,
    LlmGatewayError,
    LlmOutputParseError,
    MaxDepthExceededError,
    MetadataUpdateConflictError,
    PlanGenerationError,
    PlanParseError,
    RegistrationInconsistencyError,
    RuntimeStateUpdateConflictError,
    SemanticSearchNotEnabledError,
    TaskNotFoundError,
    ToolDefinitionError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolPermissionError,
    ToolValidationError,
)
from .interfaces import EventBus
from .models import (
    Actor,
    ActorMeta,
    ActorResponse,
    DeterministicActor,
    ExecutionContext,
    GroupState,
    GroupTurn,
    LlmConfig,
    MemoryContext,
    MemoryItem,
    ParameterDef,
    Plan,
    PlannedTask,
    RoleRouterConfig,
    RouterRule,
    Task,
    TaskBatchItem,
    TaskResult,
    TaskRuntimeState,
    ToolCall,
    ToolCapabilitySummary,
    ToolResult,
    ToolSchema,
)

__all__ = [
    # enums
    "TaskStatus",
    "ActorResponseType",
    "MemoryType",
    "MemorySource",
    "ToolCategory",
    "CollaborationStrategy",
    # exceptions
    "TaskNotFoundError",
    "InvalidStatusTransitionError",
    "InvalidTaskStateError",
    "MetadataUpdateConflictError",
    "RuntimeStateUpdateConflictError",
    "CircularDependencyError",
    "DependencyNotFoundError",
    "MaxDepthExceededError",
    "DuplicateRefIdError",
    "ActorNotFoundError",
    "DuplicateActorError",
    "InvalidActorError",
    "ActorDefinitionError",
    "ToolNotFoundError",
    "ToolPermissionError",
    "ToolValidationError",
    "DuplicateToolError",
    "ToolDefinitionError",
    "ToolExecutionError",
    "SemanticSearchNotEnabledError",
    "PlanParseError",
    "PlanGenerationError",
    "GroupStateSerializationError",
    "LlmGatewayError",
    "LlmOutputParseError",
    "RegistrationInconsistencyError",
    "ContextBuildError",
    # interfaces + impl
    "EventBus",
    "InMemoryEventBus",
    # config
    "RuntimeConfig",
    "MemoryConfig",
    "LlmGatewayConfig",
    # models
    "Actor",
    "DeterministicActor",
    "TaskResult",
    "Task",
    "TaskRuntimeState",
    "TaskBatchItem",
    "ExecutionContext",
    "ActorResponse",
    "ParameterDef",
    "ToolSchema",
    "ToolCall",
    "ToolResult",
    "MemoryItem",
    "MemoryContext",
    "PlannedTask",
    "Plan",
    "RouterRule",
    "RoleRouterConfig",
    "LlmConfig",
    "GroupTurn",
    "GroupState",
    "ToolCapabilitySummary",
    "ActorMeta",
    # events
    "TaskCreated",
    "TaskStarted",
    "TaskCompleted",
    "TaskFailed",
    "TaskWaitingInput",
    "TaskWaitingDependency",
    "TaskUnblocked",
    "TaskResumed",
    "StepProgress",
]